### ISSUE TITLE
[feature proposée]  intégrer des dispositifs d'aides et/ou des services locaux/tiers

### ISSUE THREAD

**Issue by juliencarnot** [betagouv/mpal#47]
Au delà des aides de l'ANAH, beaucoup d'acteurs peuvent intervenir pour accompagner financièrement ou techniquement une rénovation. Il peut s'agir d'aides publiques, ou de services de conseils spécialisés en performance énergétique, de services de maîtrise d'ouvrage proposés par un acteur parapublic ou privé.

Ces dispositifs peuvent être dans certains cas plus déterminants dans le déclenchement des travaux et dans leur réussite que l'aide financière. Permettre à leurs porteurs de contribuer aux données MPAL et de proposer le service de demande MPAL offre une plus grande exhaustivité aux demandeurs, mais génère aussi une plus grande adhésion des acteurs de la rénovation et potentiellement une meilleure visibilité pour MPAL, surtout [si des API permettent à chaque acteur d'intégrer MPAL à leur site](46).

Une publication open-data des données sur l'ensemble des dispositifs (critères, territoires, conditions et modalités de paiement) permettrait également d'avoir une meilleure analyse des recouvrements entre dispositifs ou des lacunes existantes.

**Comment by annemarie35** [comment]
Merci Julien pour toutes ces propositions.
